on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Tara-Cloud/push-files-to-another-repository@v1.0.0
        with:
          who-to-greet: 'Tara'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
