name: Sync TryHackMe writeups to Blog

on:
  push:
    paths:
      - 'tryhackme-room-writeups/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "tara.schoenherr@gmail.com"
          git config --global user.name "Tara-Cloud"

      - name: Sync directory
        env:
          TARGET_REPO: https://github.com/Tara-Cloud/vercel-personal-site.git
          TARGET_REPO_TOKEN: ${{ secrets.BLOG_SYNC_TOKEN }}
          SOURCE_DIR: tryhackme-room-writeups
          TARGET_DIR: src/pages/blog/tryhackme/tryhackme-room-writeups
        run: |
          # Clone the target repository
          git clone $TARGET_REPO target-repo
          # Navigate into the target repository directory
          cd target-repo
          # Checkout a new branch for the changes
          git checkout -b sync-branch
          # Remove existing contents of TARGET_DIR (optional)
          rm -rf $TARGET_DIR
          # Copy the SOURCE_DIR contents to the target directory
          cp -R ../$SOURCE_DIR ./$TARGET_DIR
          # Add and commit changes
          git add .
          git commit -m "Sync $SOURCE_DIR from source repository"
          # Push changes using the PAT for authentication
          git push --set-upstream origin sync-branch -f https://${TARGET_REPO_TOKEN}@${TARGET_REPO#https://}
