name: Sync TryHackMe writeups to Blog

on:
  push:
    paths:
      - 'tryhackme-room-writeups/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Push updated TryHackMe dir to corresponding blog directory
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'tryhackme-room-writeups/'
          destination-username: 'Tara-Cloud'
          destination-repository: 'https://github.com/Tara-Cloud/vercel-personal-site.git'
          destination-directory: 'src/pages/blog/tryhackme/tryhackme-room-writeups'
          destination-branch: 'main'
          commit-email: 'tara.schoenherr@gmail.com'
